### ISSUE TITLE
Roadmap to move organizer tools to self-maintained or dweb services

### ISSUE THREAD

**Issue by benhylau** [dweb-camp-2019/organizing#7]
Identify dependencies on centralized platforms and discuss migration to self-maintained infrastructure. The [PRISM Break project](https://prism-break.org/en/all/) has a good list for alternative tools.

- [x] Identify our current "tool stack" as organizers (ongoing)
- [x] Discuss what we hope to accomplish for this year (retrospective)
- [ ] ~~Create new tickets for migration plan (post-retrospective)~~

**Comment by benhylau** [comment]
List of current "tool stack". Updated as we identify more.

## Real-time chat
- Slack (private & public orgs)
- Matrix (bridged)
- IRC (bridge)

## Media assets
- Internet Archive
- Google Drive

## Documents
- Google docs & sheets
- GitHub markdown

## Sign-ups
- Google forms
- Eventbrite

## Mailing list
- Mailchimp
- Eventbrite mail

## Website
- Custom and self-hosted

## Blog
- Medium

## Schedule
- SCHED

## Discussions
- GitHub issues
- SSB

## Code
- GitHub repo

## Social Media
- Twitter

## Calendar
- Google calendar

## Video chat
- Zoom
- Jitsi

**Comment by gobengo** [comment]
My biggest project these days is https://permanent.cloud, which is a good place to browse for more tools. I'm also passionate about getting hacktivist conferences using FOSS tools (e.g. one might use [TellForm](https://permanent.cloud/apps/tellform) self-hosted instead of Google Forms).

Or I love using [Matomo](https://permanent.cloud/apps/matomo) for web analytics (nee Google Analytics), and that may be helpful once a website is up. I use it for permanent.cloud's website (https://matomo.permanent.cloud), and have started hosting for other organizations, such as conserve.org.

I hope also to lobby MyData to use more FOSS tools for it's conference in September, so this could be a good trial run.

Happy to provide elastic hosting of these web apps if it helps. Gonna have to do it eventually anyway, and the sooner I can learn from real use cases the better.

**Comment by benhylau** [comment]
Self-hosting conference management software is probably useful so we can also bring a copy to the local network: http://frab.github.io/frab/

@whanamura this is what they used for [ToorCamp 2018](https://frab.toorcon.net/en/toorcamp2018/public/schedule) and CCC.

**Comment by benhylau** [comment]
## Ticketing tool

Attendees are paying a lot of 💸 for processing of ticket sales. There is a payment processing fee of 2.5% charged by payment processors, which sort of establishes a baseline cost, but **$1 + %-based fee structure per ticket** is not the best option for DWeb given high ticket costs.

We should investigate solutions that offer fixed monthly costs, such as [Event Smart](https://eventsmart.com/pricing/) where we pay a fixed charge of ~$100 per month where tickets are on sale, regardless of how many tickets are sold, and only the payment processing 2.5% is transferred to registrants.

[More info](https://eventsmart.com/compare/eventbrite-vs-event-smart-right-event-business/) about the difference in fee models.

**Comment by benhylau** [comment]
## Accounting requirements

For money going out to support individuals (e.g. Global Fellows), these are the information that Internet Archive Accounting needs to gather before sending money:

```
The name of the person
Their address as listed with their bank (for wires)
Their address (if a check is issued)
A W-9 form for US residents  (form attached)

Also bank info:
Name of Bank
Branch name
Address of Branch
Swift code
IBAN account #
```
[Blank W-9.pdf](https://github.com/dweb-camp-2019/organizing/files/3318744/Blank.W-9.pdf)

**Comment by benhylau** [comment]
## Programming

Current process is quite labour intensive, the information flows through stages like this and someone has to quite manually be involved at each process, with some back and forth emailing in between:

1. Pre-discussions on Matrix / GitHub / Emails / SSB (fragmented)
1. Project leaders to submit Google Forms:
    - [Projects](https://docs.google.com/forms/d/1Iet2xk6qwZZWkDHTEMCUn5zlb80IwXNtb6epk4-9O-s/)
    - [Lightning Talks](https://docs.google.com/forms/d/1BEqSJtzagzEu4vUCnGNZquSJl8FpzZd7n7QanNS9fEk/)
1. Enter data from submitted Forms into website CMS (require presenter info collected from previous years or by manual email)
1. Space-time spreadsheet (slot sessions into venue space, coordinate with _Space Weavers_)
1. @whanamura + Space Weavers + Project Leaders to put data into SCHED (with API if needed)

**Comment by benhylau** [comment]
## Invitation for Immigration Services

We need the following information about each applicant in order to issue an invitation letter. This is currently edited over email exchange, occasionally requiring clarifications and corrections, and each time we change in a word documenting and print as PDF with Internet Archive letterhead. We should have a tool to collect applicant information then generate via `markdown-pdf`.

First name:
Surname:
Date of birth:
Passport number:
Expiry date:
Nationality:

**Short description of why applicant is invited:**

**Short description of financial sponsor:**

**Short description of accommodation arrangement (if not at Internet Archive):**

- [ ] Is this for a travel visa application?

**Comment by benhylau** [comment]
>Discuss what we hope to accomplish for this year (retrospective)

@whanamura in our brief discussion earlier this week, I think we agreed to publish a _Services Inventory_ to reflect the current tools we use, with recommendations for future on some items, and revisit in the future.

>Create new tickets for migration plan (post-retrospective)

So I think new tickets will be a next-year activity.
